apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
resources:
- namespace.yaml
- secret.yaml
- ../../../base/be


patches:
- path: domain.json
  target:
    kind: Ingress
    name: be-ingress
images:
- name: scgskku/ask-be
  newTag: 75a0343c3328e198874d08413ac69162b43942e2-backend
