apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
resources:
- namespace.yaml
- secret.yaml
- ../../../base/be


patches:
- path: domain.json
  target:
    kind: Ingress
    name: be-ingress
images:
- name: scgskku/ask-be
  newTag: fe723091ac492bb8c830ace5c9ad0f1397954936-backend
