apiVersion: v1
kind: Secret
metadata:
  name: ask-secret-be
type: Opaque
data:
  SMTP_USERNAME: <path:kv/data/ask-secret#smtp_username | base64encode>
  SMTP_PASSWORD: <path:kv/data/ask-secret#smtp_password | base64encode>
  
