apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: 229c4a72ad98a1b24a153f70168bf6ccaba7b177-frontend
resources:
- ../../../base/fe
- secret.yaml
