apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: 75a0343c3328e198874d08413ac69162b43942e2-frontend
resources:
- ../../../base/fe
- secret.yaml
