apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: 244f1278736c94e860c49a107945183cfa60f270-frontend
resources:
- ../../../base/fe
- secret.yaml
