apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: fe723091ac492bb8c830ace5c9ad0f1397954936-frontend
resources:
- ../../../base/fe
- secret.yaml
