apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: 07505e20b3a5e137e88a540ae213ab11224caad4-frontend
resources:
- ../../../base/fe
- secret.yaml
