apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-ask
patches:
- path: domain.json
  target:
    kind: Ingress
    name: fe-ingress
images:
- name: scgskku/ask-fe
  newTag: 9b608bcd0574502f357deafeefb21e35ad1f1750-frontend
resources:
- ../../../base/fe
- secret.yaml
